# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'entry_sale.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1302, 712)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 12, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #333;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 7, 1, 1)
        self.sub_total = QtWidgets.QLabel(self.centralwidget)
        self.sub_total.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #333;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"")
        self.sub_total.setObjectName("sub_total")
        self.gridLayout.addWidget(self.sub_total, 6, 7, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #333;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #333;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 7, 1, 1)
        self.entry_location_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_location_line_edit.setStyleSheet("QLineEdit{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-bottom: 1px solid #aaa;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"QLineEdit:hover {   \n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-bottom: 1px solid #000;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"}\n"
"")
        self.entry_location_line_edit.setObjectName("entry_location_line_edit")
        self.gridLayout.addWidget(self.entry_location_line_edit, 3, 2, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #333;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 8, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #333;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 7, 1, 1)
        self.entry_invoice_id_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_invoice_id_line_edit.setStyleSheet("QLineEdit{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-bottom: 1px solid #aaa;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"QLineEdit:hover {   \n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-bottom: 1px solid #000;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"}\n"
"")
        self.entry_invoice_id_line_edit.setObjectName("entry_invoice_id_line_edit")
        self.gridLayout.addWidget(self.entry_invoice_id_line_edit, 0, 2, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #333;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 6, 5, 1, 1)
        self.entry_address_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_address_line_edit.setStyleSheet("QLineEdit{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-bottom: 1px solid #aaa;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"QLineEdit:hover {   \n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-bottom: 1px solid #000;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"}\n"
"")
        self.entry_address_line_edit.setObjectName("entry_address_line_edit")
        self.gridLayout.addWidget(self.entry_address_line_edit, 2, 2, 1, 3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #333;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.print_btn = QtWidgets.QPushButton(self.centralwidget)
        self.print_btn.setStyleSheet("QPushButton{\n"
"    background-color: #ddd;\n"
"    border: 1px solid #aaa;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {   \n"
"    background-color: #bbf;\n"
"    border: 1px solid #000;\n"
"    color: #fff;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.print_btn.setObjectName("print_btn")
        self.gridLayout.addWidget(self.print_btn, 6, 10, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 6, 1, 1)
        self.save_n_new_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_n_new_btn.setStyleSheet("QPushButton{\n"
"    background-color: #ddd;\n"
"    border: 1px solid #aaa;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {   \n"
"    background-color: #bbf;\n"
"    border: 1px solid #000;\n"
"    color: #fff;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.save_n_new_btn.setObjectName("save_n_new_btn")
        self.gridLayout.addWidget(self.save_n_new_btn, 6, 2, 1, 3)
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setStyleSheet("QPushButton{\n"
"    background-color: #ddd;\n"
"    border: 1px solid #aaa;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {   \n"
"    background-color: #bbf;\n"
"    border: 1px solid #000;\n"
"    color: #fff;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #333;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.save_n_exit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_n_exit_btn.setStyleSheet("QPushButton{\n"
"    background-color: #ddd;\n"
"    border: 1px solid #aaa;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {   \n"
"    background-color: #bbf;\n"
"    border: 1px solid #000;\n"
"    color: #fff;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.save_n_exit_btn.setObjectName("save_n_exit_btn")
        self.gridLayout.addWidget(self.save_n_exit_btn, 6, 9, 1, 1)
        self.entry_customer_id_combo = QtWidgets.QComboBox(self.centralwidget)
        self.entry_customer_id_combo.setObjectName("entry_customer_id_combo")
        self.gridLayout.addWidget(self.entry_customer_id_combo, 1, 2, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #333;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 1, 1, 1)
        self.select_location_btn = QtWidgets.QPushButton(self.centralwidget)
        self.select_location_btn.setStyleSheet("QPushButton{\n"
"    background-color: #ddd;\n"
"    border: 1px solid #aaa;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {   \n"
"    background-color: #bbf;\n"
"    border: 1px solid #000;\n"
"    color: #fff;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.select_location_btn.setObjectName("select_location_btn")
        self.gridLayout.addWidget(self.select_location_btn, 5, 10, 1, 1)
        self.file_location_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.file_location_line_edit.setStyleSheet("QLineEdit{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-bottom: 1px solid #aaa;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"QLineEdit:hover {   \n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-bottom: 1px solid #000;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"}\n"
"")
        self.file_location_line_edit.setObjectName("file_location_line_edit")
        self.gridLayout.addWidget(self.file_location_line_edit, 5, 2, 1, 8)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.entry_product_id_combo = QtWidgets.QComboBox(self.frame)
        self.entry_product_id_combo.setObjectName("entry_product_id_combo")
        self.gridLayout_2.addWidget(self.entry_product_id_combo, 0, 0, 1, 1)
        self.entry_quantity_spin = QtWidgets.QSpinBox(self.frame)
        self.entry_quantity_spin.setMaximum(100000)
        self.entry_quantity_spin.setObjectName("entry_quantity_spin")
        self.gridLayout_2.addWidget(self.entry_quantity_spin, 0, 2, 1, 1)
        self.entry_add_btn = QtWidgets.QPushButton(self.frame)
        self.entry_add_btn.setStyleSheet("QPushButton{\n"
"    background-color: #ddd;\n"
"    border: 1px solid #aaa;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {   \n"
"    background-color: #bbf;\n"
"    border: 1px solid #000;\n"
"    color: #fff;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.entry_add_btn.setObjectName("entry_add_btn")
        self.gridLayout_2.addWidget(self.entry_add_btn, 0, 3, 1, 1)
        self.entry_product_name_combo = QtWidgets.QComboBox(self.frame)
        self.entry_product_name_combo.setObjectName("entry_product_name_combo")
        self.gridLayout_2.addWidget(self.entry_product_name_combo, 0, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 781, 447))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.entry_table = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_table.sizePolicy().hasHeightForWidth())
        self.entry_table.setSizePolicy(sizePolicy)
        self.entry_table.setObjectName("entry_table")
        self.entry_table.setColumnCount(0)
        self.entry_table.setRowCount(0)
        self.gridLayout_3.addWidget(self.entry_table, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 4)
        self.gridLayout.addWidget(self.frame, 4, 1, 1, 7)
        self.product_list = QtWidgets.QScrollArea(self.centralwidget)
        self.product_list.setWidgetResizable(True)
        self.product_list.setObjectName("product_list")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 381, 496))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.product_list.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.product_list, 4, 8, 1, 4)
        self.booking_date = QtWidgets.QDateEdit(self.centralwidget)
        self.booking_date.setObjectName("booking_date")
        self.gridLayout.addWidget(self.booking_date, 1, 8, 1, 1)
        self.delivery_date = QtWidgets.QDateEdit(self.centralwidget)
        self.delivery_date.setObjectName("delivery_date")
        self.gridLayout.addWidget(self.delivery_date, 2, 8, 1, 1)
        self.entry_employee_name_combo = QtWidgets.QComboBox(self.centralwidget)
        self.entry_employee_name_combo.setObjectName("entry_employee_name_combo")
        self.gridLayout.addWidget(self.entry_employee_name_combo, 0, 8, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #333;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 7, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #333;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 9, 1, 1)
        self.paidSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.paidSpinBox.setMaximum(1e+33)
        self.paidSpinBox.setObjectName("paidSpinBox")
        self.gridLayout.addWidget(self.paidSpinBox, 3, 8, 1, 1)
        self.discountSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.discountSpinBox.setStyleSheet("")
        self.discountSpinBox.setMaximum(1e+81)
        self.discountSpinBox.setObjectName("discountSpinBox")
        self.gridLayout.addWidget(self.discountSpinBox, 3, 10, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sale Window"))
        self.label_7.setText(_translate("MainWindow", "Delivery Date"))
        self.sub_total.setText(_translate("MainWindow", "0.00"))
        self.label_3.setText(_translate("MainWindow", "Address"))
        self.label_5.setText(_translate("MainWindow", "Employee Name"))
        self.label_8.setText(_translate("MainWindow", "Sub Total"))
        self.label_6.setText(_translate("MainWindow", "Booking Date"))
        self.label_4.setText(_translate("MainWindow", "Location"))
        self.label.setText(_translate("MainWindow", "Invoice ID"))
        self.print_btn.setText(_translate("MainWindow", "Print"))
        self.save_n_new_btn.setText(_translate("MainWindow", "Save and New"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.label_2.setText(_translate("MainWindow", "Customer ID"))
        self.save_n_exit_btn.setText(_translate("MainWindow", "Save and Exit"))
        self.label_9.setText(_translate("MainWindow", "File Location"))
        self.select_location_btn.setText(_translate("MainWindow", "Select"))
        self.entry_add_btn.setText(_translate("MainWindow", "ADD"))
        self.label_10.setText(_translate("MainWindow", "Paid"))
        self.label_11.setText(_translate("MainWindow", "Discount"))
