# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'library_add_product.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 450)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.save_n_exit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_n_exit_btn.setObjectName("save_n_exit_btn")
        self.gridLayout.addWidget(self.save_n_exit_btn, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 4, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.save_n_new_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_n_new_btn.setObjectName("save_n_new_btn")
        self.gridLayout.addWidget(self.save_n_new_btn, 4, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 4, 4, 1, 1)
        self.product_name = QtWidgets.QLineEdit(self.centralwidget)
        self.product_name.setObjectName("product_name")
        self.gridLayout.addWidget(self.product_name, 1, 2, 1, 4)
        self.product_id = QtWidgets.QLineEdit(self.centralwidget)
        self.product_id.setObjectName("product_id")
        self.gridLayout.addWidget(self.product_id, 0, 2, 1, 2)
        self.unit_price = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.unit_price.setMaximum(1e+17)
        self.unit_price.setSingleStep(0.01)
        self.unit_price.setObjectName("unit_price")
        self.gridLayout.addWidget(self.unit_price, 2, 2, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.save_n_exit_btn.setText(_translate("MainWindow", "Save and Exit"))
        self.label_3.setText(_translate("MainWindow", "Unit Price"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.label_2.setText(_translate("MainWindow", "Product Name"))
        self.save_n_new_btn.setText(_translate("MainWindow", "Save and New"))
        self.label.setText(_translate("MainWindow", "Product ID"))
