# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(447, 284)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.LoginButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoginButton.setObjectName("LoginButton")
        self.gridLayout.addWidget(self.LoginButton, 4, 1, 1, 1)
        self.PassLabel = QtWidgets.QLabel(self.centralwidget)
        self.PassLabel.setObjectName("PassLabel")
        self.gridLayout.addWidget(self.PassLabel, 3, 0, 1, 1)
        self.EmailLabel = QtWidgets.QLabel(self.centralwidget)
        self.EmailLabel.setObjectName("EmailLabel")
        self.gridLayout.addWidget(self.EmailLabel, 2, 0, 1, 1)
        self.PassLine = QtWidgets.QLineEdit(self.centralwidget)
        self.PassLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PassLine.setObjectName("PassLine")
        self.gridLayout.addWidget(self.PassLine, 3, 1, 1, 1)
        self.RegisterButton = QtWidgets.QPushButton(self.centralwidget)
        self.RegisterButton.setObjectName("RegisterButton")
        self.gridLayout.addWidget(self.RegisterButton, 4, 0, 1, 1)
        self.EmailLine = QtWidgets.QLineEdit(self.centralwidget)
        self.EmailLine.setObjectName("EmailLine")
        self.gridLayout.addWidget(self.EmailLine, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.LoginButton.setText(_translate("MainWindow", "Login"))
        self.PassLabel.setText(_translate("MainWindow", "Password*"))
        self.EmailLabel.setText(_translate("MainWindow", "Email*"))
        self.RegisterButton.setText(_translate("MainWindow", "Register"))
