# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(447, 284)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.RegisterButton = QtWidgets.QPushButton(self.centralwidget)
        self.RegisterButton.setStyleSheet("QPushButton{\n"
"    background-color: #ddd;\n"
"    border: 1px solid #aaa;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {   \n"
"    background-color: #bbf;\n"
"    border: 1px solid #000;\n"
"    color: #fff;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"")
        self.RegisterButton.setObjectName("RegisterButton")
        self.gridLayout.addWidget(self.RegisterButton, 5, 0, 1, 1)
        self.EmailLabel = QtWidgets.QLabel(self.centralwidget)
        self.EmailLabel.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #333;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"")
        self.EmailLabel.setObjectName("EmailLabel")
        self.gridLayout.addWidget(self.EmailLabel, 2, 0, 1, 1)
        self.PassLine = QtWidgets.QLineEdit(self.centralwidget)
        self.PassLine.setStyleSheet("QLineEdit{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-bottom: 1px solid #aaa;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"QLineEdit:hover {   \n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-bottom: 1px solid #000;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"}\n"
"")
        self.PassLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PassLine.setObjectName("PassLine")
        self.gridLayout.addWidget(self.PassLine, 3, 1, 1, 1)
        self.PassLabel = QtWidgets.QLabel(self.centralwidget)
        self.PassLabel.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #333;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"")
        self.PassLabel.setObjectName("PassLabel")
        self.gridLayout.addWidget(self.PassLabel, 3, 0, 1, 1)
        self.checkBox_remember_me = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_remember_me.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: #333;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"")
        self.checkBox_remember_me.setObjectName("checkBox_remember_me")
        self.gridLayout.addWidget(self.checkBox_remember_me, 4, 0, 1, 1)
        self.LoginButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoginButton.setStyleSheet("QPushButton{\n"
"    background-color: #ddd;\n"
"    border: 1px solid #aaa;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {   \n"
"    background-color: #bbf;\n"
"    border: 1px solid #000;\n"
"    color: #fff;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"")
        self.LoginButton.setObjectName("LoginButton")
        self.gridLayout.addWidget(self.LoginButton, 5, 1, 1, 1)
        self.EmailLine = QtWidgets.QLineEdit(self.centralwidget)
        self.EmailLine.setStyleSheet("QLineEdit{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-bottom: 1px solid #aaa;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"}\n"
"\n"
"QLineEdit:hover {   \n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-bottom: 1px solid #000;\n"
"    color: #555;\n"
"    box-sizing: border-box;\n"
"    font-family: \'Arvo\';\n"
"    font-size: 14px;\n"
"    padding: 2px 0px;\n"
"}\n"
"")
        self.EmailLine.setObjectName("EmailLine")
        self.gridLayout.addWidget(self.EmailLine, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.RegisterButton.setText(_translate("MainWindow", "Register"))
        self.EmailLabel.setText(_translate("MainWindow", "Email*"))
        self.PassLabel.setText(_translate("MainWindow", "Password*"))
        self.checkBox_remember_me.setText(_translate("MainWindow", "Remember Me"))
        self.LoginButton.setText(_translate("MainWindow", "Login"))
