# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(501, 337)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pass_confirm_reg = QtWidgets.QLineEdit(self.centralwidget)
        self.pass_confirm_reg.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_confirm_reg.setObjectName("pass_confirm_reg")
        self.gridLayout.addWidget(self.pass_confirm_reg, 4, 1, 1, 1)
        self.last_name_reg = QtWidgets.QLineEdit(self.centralwidget)
        self.last_name_reg.setObjectName("last_name_reg")
        self.gridLayout.addWidget(self.last_name_reg, 1, 1, 1, 1)
        self.reg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reg_btn.setObjectName("reg_btn")
        self.gridLayout.addWidget(self.reg_btn, 5, 1, 1, 1)
        self.pass_reg = QtWidgets.QLineEdit(self.centralwidget)
        self.pass_reg.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_reg.setObjectName("pass_reg")
        self.gridLayout.addWidget(self.pass_reg, 3, 1, 1, 1)
        self.first_name_reg = QtWidgets.QLineEdit(self.centralwidget)
        self.first_name_reg.setObjectName("first_name_reg")
        self.gridLayout.addWidget(self.first_name_reg, 0, 1, 1, 1)
        self.email_reg = QtWidgets.QLineEdit(self.centralwidget)
        self.email_reg.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.email_reg.setObjectName("email_reg")
        self.gridLayout.addWidget(self.email_reg, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Register"))
        self.reg_btn.setText(_translate("MainWindow", "Register"))
        self.label.setText(_translate("MainWindow", "First Name*"))
        self.label_2.setText(_translate("MainWindow", "Last Name*"))
        self.label_3.setText(_translate("MainWindow", "Email*"))
        self.label_4.setText(_translate("MainWindow", "Password*"))
        self.label_5.setText(_translate("MainWindow", "Confirm Password*"))
